project:
  type: website

website:
  title: "Lluís Navarro-Girbés" 
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Data Projects
        href: projects.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/falken1983
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual